/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a134b27b-1334-4d9b-890f-38f9601ea250",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_5jnXfJght",
    "aws_user_pools_web_client_id": "8sj84b7910if2r7psluqfoat9",
    "oauth": {}
};


export default awsmobile;
